Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -78,9 +78,43 @@ commands: &set_terraform_environment
             # "PARAM_ROLE_SESSION_NAME=$(eval echo \"${PARAM_ROLE_SESSION_NAME}\")\nPARAM_AWS_CLI_ROLE_ARN=$(eval echo \"${PARAM_AWS_CLI_ROLE_ARN}\")\n\nif [ -z \"${PARAM_ROLE_SESSION_NAME}\" ]; then\n echo \"Role session name is required\"\n exit 1\nfi\n\nif [ -z \"${CIRCLE_OIDC_TOKEN}\" ]; then\n echo \"OIDC Token cannot be found. A CircleCI context must be specified.\"\n exit 1\nfi\n\nif [ ! \"$(command -v aws)\" ]; then\n echo \"AWS CLI is not installed. Please run the setup or install command first.\"\n exit 1\nfi\n\nread -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \\<<EOF\n$(aws sts assume-role-with-web-identity \\\n--role-arn \"${PARAM_AWS_CLI_ROLE_ARN}\" \\\n--role-session-name \"${PARAM_ROLE_SESSION_NAME}\" \\\n--web-identity-token \"${CIRCLE_OIDC_TOKEN}\" \\\n--duration-seconds \"${PARAM_SESSION_DURATION}\" \\\n--query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \\\n--output text)\nEOF\n\nif [ -z \"${AWS_ACCESS_KEY_ID}\" ] || [ -z \"${AWS_SECRET_ACCESS_KEY}\" ] || [ -z \"${AWS_SESSION_TOKEN}\" ]; then\n echo \"Failed to assume role\";\n exit 1\nelse \n {\n echo \"export AWS_ACCESS_KEY_ID=\\\"${AWS_ACCESS_KEY_ID}\\\"\"\n echo \"export AWS_SECRET_ACCESS_KEY=\\\"${AWS_SECRET_ACCESS_KEY}\\\"\"\n echo \"export AWS_SESSION_TOKEN=\\\"${AWS_SESSION_TOKEN}\\\"\"\n } >>\"$BASH_ENV\"\n echo \"Assume role with web identity succeeded\"\n echo \"export TERRAFORM_ENVIRONMENT=terraform-dev-aws\">>\"$BASH_ENV\"\nfi\n"
             # fi
           command: |
-            if [ $CIRCLE_BRANCH == "main" ] then;
-             "PARAM_ROLE_SESSION_NAME=$(eval echo \"${PARAM_ROLE_SESSION_NAME}\")\nPARAM_AWS_CLI_ROLE_ARN=$(eval echo \"${PARAM_AWS_CLI_ROLE_ARN}\")\n\nif [ -z \"${PARAM_ROLE_SESSION_NAME}\" ]; then\n echo \"Role session name is required\"\n exit 1\nfi\n\nif [ -z \"${CIRCLE_OIDC_TOKEN}\" ]; then\n echo \"OIDC Token cannot be found. A CircleCI context must be specified.\"\n exit 1\nfi\n\nif [ ! \"$(command -v aws)\" ]; then\n echo \"AWS CLI is not installed. Please run the setup or install command first.\"\n exit 1\nfi\n\nread -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \\<<EOF\n$(aws sts assume-role-with-web-identity \\\n--role-arn \"${PARAM_AWS_CLI_ROLE_ARN}\" \\\n--role-session-name \"${PARAM_ROLE_SESSION_NAME}\" \\\n--web-identity-token \"${CIRCLE_OIDC_TOKEN}\" \\\n--duration-seconds \"${PARAM_SESSION_DURATION}\" \\\n--query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \\\n--output text)\nEOF\n\nif [ -z \"${AWS_ACCESS_KEY_ID}\" ] || [ -z \"${AWS_SECRET_ACCESS_KEY}\" ] || [ -z \"${AWS_SESSION_TOKEN}\" ]; then\n echo \"Failed to assume role\";\n exit 1\nelse \n {\n echo \"export AWS_ACCESS_KEY_ID=\\\"${AWS_ACCESS_KEY_ID}\\\"\"\n echo \"export AWS_SECRET_ACCESS_KEY=\\\"${AWS_SECRET_ACCESS_KEY}\\\"\"\n echo \"export AWS_SESSION_TOKEN=\\\"${AWS_SESSION_TOKEN}\\\"\"\n } >>\"$BASH_ENV\"\n echo \"Assume role with web identity succeeded\"\n echo \"export TERRAFORM_ENVIRONMENT=terraform-dev-aws\">>\"$BASH_ENV\"\nfi\n"
-            fi
+        
+             
+case "$CIRCLE_BRANCH" in
+  "circleci_terraform")
+    PARAM_ROLE_SESSION_NAME=$(eval echo "${PARAM_ROLE_SESSION_NAME}")
+    PARAM_AWS_CLI_ROLE_ARN=$(eval echo "${PARAM_AWS_CLI_ROLE_ARN_DEV}")
+    if [ -z "${PARAM_ROLE_SESSION_NAME}" ]; then
+      echo "Role session name is required"
+      exit 1
+    fi
+    if [ -z "${CIRCLE_OIDC_TOKEN}" ]; then
+      echo "OIDC Token cannot be found. A CircleCI context must be specified."
+      exit 1
+    fi
+    if [ ! "$(command -v aws)" ]; then
+      echo "AWS CLI is not installed. Please run the setup or install command first."
+      exit 1
+    fi
+    read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN<<EOF
+    $(aws sts assume-role-with-web-identity --role-arn "${PARAM_AWS_CLI_ROLE_ARN_DEV}" --role-session-name "${PARAM_ROLE_SESSION_NAME}" --web-identity-token "${CIRCLE_OIDC_TOKEN}" --duration-seconds "${PARAM_SESSION_DURATION}" --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text)
+    EOF
+    if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
+      echo "Failed to assume role"
+      exit 1
+    else 
+      echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"  >> $BASH_ENV
+      echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"  >> $BASH_ENV
+      echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"  >> $BASH_ENV
+
+    echo "Assume role with web identity succeeded"
+    echo "export TERRAFORM_ENVIRONMENT=terraform-dev-aws" >> $BASH_ENV
+    fi
+  ;;
+
+esac
+
+            
           environment:
               PARAM_AWS_CLI_PROFILE_NAME: <<parameters.profile-name>>
               PARAM_AWS_CLI_ROLE_ARN: <<parameters.role-arn>>
